name: 'Setup Infrastructure Tools'
description: 'Install Terramate, Terraform and Terragrunt'

runs:
  using: 'composite'
  steps:
    - name: Install Terramate
      uses: terramate-io/terramate-action@v3
      with:
        version: "0.14.0"

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.9.8"

    - name: Setup Terragrunt
      uses: autero1/action-terragrunt@v3
      with:
        terragrunt-version: 0.83.2
        token: ${{ github.token }}
