name: 'AWS OIDC Authentication'
description: 'Authenticate with AWS using OIDC'

inputs:
  aws-account-id:
    description: 'AWS Account ID'
    required: true
  aws-region:
    description: 'AWS Region'
    required: false
    default: 'us-east-1'

runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/GitHubActions-TerramateRole
